# Generated by Django 6.0.7 on 2026-07-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_user_recepionist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='customerid',
            field=models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='orderid',
            field=models.ForeignKey(blank=True, db_column='orderid', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
