# Generated by Django 6.0.7 on 2026-07-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_address_alter_customer_houseno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='serviceid',
            field=models.ForeignKey(db_column='serviceid', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.services'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
