# Generated by Django 6.0.7 on 2026-08-18 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_options_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['category', 'servicename']},
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('laundry', 'Laundry'), ('conferences', 'Conferences'), ('catering', 'Catering'), ('room_booking', 'Room Booking')], default='laundry', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='orderid',
            field=models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Tigo Pesa', 'Tigo Pesa'), ('Airtel Money', 'Airtel Money'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card')], default='M-Pesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(db_column='serviceid', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.services')),
            ],
            options={
                'db_table': 'service_items',
                'ordering': ['item_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service_item',
            field=models.ForeignKey(blank=True, db_column='service_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.serviceitem'),
        ),
    ]
