# Generated by Django 6.0.7 on 2026-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payment_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_item',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='service_description',
        ),
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceItem',
        ),
    ]
