# Generated by Django 6.0.7 on 2026-08-19 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_service_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='total_price',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recepionist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='customerid',
            field=models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='orderid',
            field=models.ForeignKey(blank=True, db_column='orderid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='serviceid',
            field=models.ForeignKey(blank=True, db_column='serviceid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.services'),
        ),
        migrations.CreateModel(
            name='ServicesItem',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('quantity', models.IntegerField(default=1)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.services')),
            ],
            options={
                'db_table': 'services_item',
                'ordering': ['itemname'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.servicesitem'),
        ),
    ]
