# Generated by Django 6.0.7 on 2026-08-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_item_id_remove_services_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='clickpesa_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(choices=[('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='tigo_pesa', max_length=20),
        ),
        migrations.CreateModel(
            name='ClickPesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickpesa_transactions', to='core.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickpesa_transactions', to='core.payment')),
            ],
            options={
                'db_table': 'clickpesa_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
